### PR TITLE
Fix compiling with vc14

### PR DESCRIPTION
**Pull request by peterlama**
See https://bugreports.qt.io/browse/PYSIDE-321. I did not get any response from upstream, so I've added the patch to this recipe.

### CODE REVIEW

**Comment by jakirkham** [comment]
Needs a build number bump as well.

**Comment by jakirkham** [comment]
...and a [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) too.

**Comment by peterlama** [comment]
Sorry, I think must have screwed up the re-render. Any idea why circleci has such an error?

**Comment by jakirkham** [comment]
Could you please try rebasing on PR ( https://github.com/conda-forge/pyside-feedstock/pull/7 )?

**Comment by jschueller** [comment]
This is great news, you can rebase now.
You'll need to push this change to https://codereview.qt-project.org, there's a 4.8 branch there.

**Comment by peterlama** [comment]
Okay, before I push the rebased branch, it looks like I need a [win] conditional for this patch since it fails applying on linux and osx, or...?

**Comment by jschueller** [comment]
yes, it seems the patch does not apply cleanly under all platforms because it's not the same line endings format as the others. I'd prefer if it'd apply cleanly on all platforms:
```
$ file recipe/*.patch
recipe/disable-failing-tests.patch:          unified diff output, ASCII text, with CRLF, LF line terminators
recipe/fix-vc2013-hash_map.patch:            unified diff output, ASCII text, with CRLF, LF line terminators
recipe/fix-vs2015-4.8.patch:                 unified diff output, ASCII text
recipe/shiboken-osx-fix-stderr-output.patch: unified diff output, ASCII text, with CRLF, LF line terminators
```

**Comment by ccordoba12** [comment]
@jschueller, should we close this one?

**Comment by jschueller** [comment]
See #10, I reworked your patch to have crlf endings BUT with some lf endifs at patch tags like the other patches (I had to remove gitattributes), that was tricky.
Thanks a lot!

**Pull request closed without merging**
