### PR TITLE
Enable osx

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jakirkham** [comment]
Needs the `osx_image` set. Please see PR ( https://github.com/conda-forge/conda-smithy/pull/325 ).

**Comment by ccordoba12** [comment]
I cancelled the builds so they don't take time for other feedstocks.

**Comment by jakirkham** [comment]
Please [re-render](https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock) with `conda-smithy`. This is required to enable the disabled CIs (e.g. Travis CI). In this particular case, it is very important to re-render with the latest release `1.3.2` to get a critical bug fix for Travis CI. Please ping when you have done this. Would like to double check that it went through smoothly.

Edit: xref: https://github.com/conda-forge/conda-forge.github.io/issues/249

**Comment by jschueller** [comment]
@jakirkham done

**Pull request merged**
