### PR TITLE
Build long prefix package using conda-build 2.x

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
Sorry, the dependencies required to build a long prefix package for this feedstock are not yet available.  Specifically `curl` needs to be re-build so that `cmake` can use used in a long prefix environment.  I'm closing this issue for the time being.  Once the long prefix version of the needed dependencies are ready I will re-open this PR or create a new PR.

**Comment by jjhelmus** [comment]
The linux long-prefix build still needs some additional packages rebuild (`glib` and `harfbuzz` at minimum).  I think this can be ignored for the time being.  I'll close and re-open this when those packages are ready.

**Comment by ocefpaf** [comment]
> `glib` and `harfbuzz` at minimum

`glib` is ready and I have a PR almost ready for `harfbuzz`. I'm only waiting for `CircleCI` to get back online.

**Comment by jschueller** [comment]
oh, I wondered why circleci wasn't starting, they do not mention the issue on their status page.

**Comment by jakirkham** [comment]
xref: https://github.com/conda-forge/status/issues/30

**Comment by jjhelmus** [comment]
Closing, will create a new PR when ready.

**Comment by jakirkham** [comment]
Replaced with PR ( https://github.com/conda-forge/pyside-feedstock/pull/11 ).

**Pull request closed without merging**
