### PR TITLE
Build long prefix package using conda-build 2.x

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
Not sure what to do about the OS X build exceeding the maximum time limit.  Any suggestions?

**Comment by jakirkham** [comment]
Considering both the Travis CI and AppVeyor builds that went over do not typically go over the time limit and don't typically take that long to build, I'm guessing this is a sporadic hang. Have restarted the one Travis CI build that had this issue and the AppVeyor builds (as I could not restart the single one that went over). Let's see if the issue doesn't just go away on its own. If it does, I'm inclined to merge and click restart as many times as necessary to get all the packages built. We can note this problem in a new issue on this feedstock.

**Comment by jakirkham** [comment]
Looks like that worked. @jschueller , could you please take a look at this one as well?

**Comment by jschueller** [comment]
looks ok

**Comment by jakirkham** [comment]
Sorry I totally missed that we didn't have a build number bump. 😞

Added PR ( https://github.com/conda-forge/pyside-feedstock/pull/12 ) to bump the build number.

**Pull request merged**
